version: '3.8'

services:

  person:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/app
    environment:
      - FLASK_APP=person
      - FLASK_ENV=development