version: '3.8'

services:

  pycroservice:
    build:
      context: ../services/
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: $SERVICE_NAME
    ports:
      - "5000"
    volumes:
      - ../services/$SERVICE_NAME:/app
    environment:
      - FLASK_ENV=development