name: Example service CI

on:
  pull_request:
    branches:
      - main

jobs:
  example_service:
    uses: DLukeNelson/pycroservices/.github/workflows/service.yml@main
    with:
      service_name: example