name: Person service CI

on:
  pull_request:
    branches:
      - main
    paths:
      - services/person/**
      - services/*

jobs:
  person_service:
    uses: DLukeNelson/pycroservices/.github/workflows/service.yml@main
    with:
      service_name: person