name: Person service CI

on:
  pull_request:
    branches:
      - main

jobs:
  person_service:
    uses: DLukeNelson/pycroservices/.github/workflows/service.yml@main
    with:
      service_name: person