name: Pycroservice CI

on:
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./services
          build-args: SERVICE_NAME=person
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: person_pycroservice:latest
          outputs: type=docker,dest=/tmp/person.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: person
          path: /tmp/person.tar

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: person
          path: /tmp
      
      - name: Load image
        run: docker load --input /tmp/person.tar
      
      - name: run
        run: ./scripts/run.sh person

      - name: lint
        run: ./scripts/lint.sh person

      - name: test
        run: ./scripts/test.sh person
